drawable size attribute added
Omega-R/OmegaCenterIconButton pull request #10
Opened 2019-07-31 07:23 UTC by R12rus

2019-07-31 07:27 UTC, scrinoman requested changes

2019-07-31 07:27 UTC, scrinoman commented on build.gradle
> +    ext.target_Sdk_Version = 28
lowerSnakeCamelCase? вроде бы такой нотации вообще не существует

2019-07-31 07:40 UTC, R12rus commented on build.gradle
> +    ext.target_Sdk_Version = 28
Ок поменяю на snake. Просто ругается теперь на minSdkVersion

2019-08-01 13:28 UTC, scrinoman approved these changes

2019-08-06 09:21 UTC, anton-knyazev requested changes

2019-08-06 09:21 UTC, anton-knyazev commented on center_icon_button/src/main/java/com/omega_r/libs/OmegaCenterIconButton.java
> +                    if (mDrawableSize != -1) {
mDrawableSize >= 0

2019-08-06 09:21 UTC, anton-knyazev commented on center_icon_button/src/main/java/com/omega_r/libs/OmegaCenterIconButton.java
> +
Зачем создавать новый Drawable? Можно только bounds указать и вызывать специальный метод setCompoundDrawables

2019-08-08 07:57 UTC, anton-knyazev approved these changes

2019-08-08 07:57 UTC, merged